export const add_expense = 'Expense/AddExpense'
export const get_expense = 'Expense/GetExpense'
export const get_this_monthly_expense_count = 'Expense/GetThisMonthlyExpensesCount'
export const get_today_expenses_count = 'Expense/GetTodayExpensesCount'
export const get_all_expenses_count = 'Expense/GetAllExpensesCount'
export const get_current_week_daily_expense_count = 'Expense/GetCurrentWeekDailyExpenseCount'
export const get_expense_by_year = 'Expense/GetExpenseByYear'
export const get_current_week_daily_income_expense_count = 'Expense/GetCurrentWeekDailyIncomeExpenseCount'
